eslint:
  enabled: true
  config_file: .eslintrc.json
  ignore_file: .eslintignore
  ignore_file: ./src/database/migrations
  ignore_file: ./src/database/seeders
  javascript:
  enabled: false

fail_on_violations: true
